### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by osbota01** [ds4owd-001/md-03-assignments-osbota01#1]
@larnsce @mianzg @sskorik01

One question - under Task 3 in Part A (penguins-practice), are both of the below code chunks valid? In particular, I'm wondering if it matters if you use the filter function with !is.na... versus na.rm=TRUE. The output looked similar but counts were slightly different. Thanks!

penguins |> 
  filter(!is.na(bill_depth_mm), !is.na(bill_length_mm)) |> 
  group_by(species, year) |> 
  summarise(bill_depth_mean = mean(bill_depth_mm),
            bill_length_mean = mean(bill_length_mm),
            count = n())

penguins |> 
  group_by(species, year) |> 
  summarise(bill_depth_mean = mean(bill_depth_mm, na.rm = TRUE),
            bill_length_mean = mean(bill_length_mm, na.rm = TRUE),
             count = n())

**Comment by larnsce** [comment]
Thank you, @osbota01.

They are both valid, but there is an important difference in the output, which you have noticed yourself: the counts.

With `filter()` you remove the NAs from the data. Your mean then represents the number of observations/values that it was calculated for. When you show the count alongside the mean, then this would be what you want.

When you add `na.rm = TRUE` to the `mean()` function, the `NAs` are removed only from the calculation of the mean, but not from the overall data. That's why the count is greater, and if you showed it in the output it would be wrong because the mean is only calculcated for the observations that are not NA.

I would recommend using `filter(!is.na(bill_depth_mm), !is.na(bill_length_mm))`, then you are save.

**Comment by larnsce** [comment]
And well done for working through the assigment. ou can see a comparison of what was deleted/edited (red - left side) and was added (green - right side) here: https://github.com/ds4owd-001/md-03-assignments-osbota01/commit/3ffd76dbd3abc7dce72bf873ebe8049d10111b79

I have added some comments. On each line, one can add comments. A bit like you would do in MS Word with comments and track changes.

Unless you have more question, you could close the issue.
